import os

libs = []
sources = ['test_u128.cc', '../liboptarithxx.a']

if os.path.isfile('/usr/local/lib/libgmp.a'):
    sources.append('/usr/local/lib/libgmp.a')
elif os.path.isfile('/usr/lib/libgmp.a'):
    sources.append('/usr/lib/libgmp.a')
else:
    libs.append('gmp')

Program(target='test_u128',
        source=sources,
        CCFLAGS=['-Wall', '-Werror', '-DNDEBUG', '-O3'],
        CPPPATH='../..',
        LIBS=libs)

