import os
import os.path

libs = ['rt']
sources = ['../liboptarithxx.a']
ccflags = ['-Wall', '-DNDEBUG', '-O3']

hasPari = os.path.exists('/usr/include/pari/pari.h') or \
          os.path.exists('/usr/local/include/pari/pari.h')

if hasPari:
   if os.path.isfile('/usr/local/lib/libpari.a'):
      sources.append('/usr/local/lib/libpari.a')
   elif os.path.isfile('/usr/lib/libpari.a'):
      sources.append('/usr/lib/libpari.a')
   else:
      libs.append('pari')
else:
   ccflags += ['-DNO_PARI']
    
if os.path.isfile('/usr/local/lib/libgmp.a'):
   sources.append('/usr/local/lib/libgmp.a')
elif os.path.isfile('/usr/lib/libgmp.a'):
   sources.append('/usr/lib/libgmp.a')
else:
   libs.append('gmp')

Program(target='timegcd',
        source=['timegcd.cc'] + sources,
        CCFLAGS=ccflags,
        CPPPATH='../..',
        LIBS=libs)

Program(target='timepartial',
        source=['timepartial.cc'] + sources,
        CCFLAGS=ccflags,
        CPPPATH='../..',
        LIBS=libs)

if hasPari:
   Program(target='timepari',
           source=['timepari.cc'] + sources,
           CCFLAGS=ccflags,
           CPPPATH='../..',
           LIBS=libs)

