import os

libs = ['rt']
sources = ['timegcd.cc', '../liboptarithxx.a']
    
if os.path.isfile('/usr/local/lib/libgmp.a'):
    sources.append('/usr/local/lib/libgmp.a')
elif os.path.isfile('/usr/lib/libgmp.a'):
    sources.append('/usr/lib/libgmp.a')
else:
    libs.append('gmp')

Program(target='timegcd',
        source=sources,
        CCFLAGS=['-Wall', '-Werror', '-DNDEBUG', '-O3'],
        CPPPATH='../..',
        LIBS=libs)

