import os

libs = ['rt', 'pari']
sources = ['timegcd.cc',
           'gcd_stein_windowed.cc',
           'gcd_pari.c',
           '../liboptarithxx.a']
    
if os.path.isfile('/usr/local/lib/libgmp.a'):
    sources.append('/usr/local/lib/libgmp.a')
elif os.path.isfile('/usr/lib/libgmp.a'):
    sources.append('/usr/lib/libgmp.a')
else:
    libs.append('gmp')

Program(target='timegcd',
        source=sources,
        CCFLAGS=['-Wall', '-DNDEBUG', '-O3'],
        CPPPATH='../..',
        LIBS=libs)

